# Generated by Django 4.0.3 on 2022-04-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_anonymousunlockspackage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousunlockspackage',
            name='tag',
            field=models.CharField(default='unlock_code', max_length=36),
            preserve_default=False,
        ),
    ]
