# Generated by Django 4.0.3 on 2022-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_anonymousunlockspackage_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousunlockspackage',
            name='tag',
            field=models.CharField(default='unlock_code_package', max_length=36),
        ),
    ]
