# Generated by Django 4.0.3 on 2022-04-10 06:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_prosubscriptionpackage_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosubscriptionpackage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='payments/products/photos/%Y/'),
        ),
    ]
