# Generated by Django 4.0.3 on 2022-04-12 07:11

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_prosubscriptionpackage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlocksPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='payments/products/photos/%Y/')),
                ('title', models.CharField(max_length=128)),
                ('unlocks', models.IntegerField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('stripe_product_id', models.CharField(max_length=96)),
                ('stripe_price_id', models.CharField(max_length=96)),
                ('expires_in', models.IntegerField()),
                ('job_cards', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('tag', models.CharField(default='unlock_code_package', max_length=36)),
            ],
            options={
                'verbose_name': 'Anonymous Unlocks Package',
                'verbose_name_plural': 'Anonymous Unlocks Packages',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='AnonymousUnlocksPackage',
        ),
        migrations.DeleteModel(
            name='ProSubscriptionPackage',
        ),
    ]
