# Generated by Django 4.0.3 on 2022-04-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_unlockspackage_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnlocksPackage',
            new_name='AccessPackage',
        ),
    ]
