# Generated by Django 4.0.3 on 2022-04-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_rename_unlockspackage_accesspackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspackage',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='accesspackage',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
