FROM python:3.9-slim-buster AS builder

# Set work directory
WORKDIR /django

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV CELERY_BROKER redis://redis:6379/0
ENV CELERY_BACKEND redis://redis:6379/0
ENV VEETA_ENV core.settings.staging

RUN apt-get update && \
    apt-get install -y cron && \
    apt-get install -y vim && \
    apt-get -y install sudo && \
    apt-get -y install libpq-dev gcc && \
    pip install psycopg2 && \
    apt-get autoremove -y && \
    apt-get clean

FROM builder AS build2

# Copy Start Scripts
COPY ./opswork/celery_entrypoint.sh /
RUN chmod +x /celery_entrypoint.sh

FROM build2 AS build3
# Create a Virtual Env
COPY ./requirements.txt requirements.txt
RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/pip install pip --upgrade
RUN /opt/venv/bin/pip install -r requirements.txt
COPY . .

RUN adduser --disabled-password --shell /bin/bash --gecos 'celeryguy' celeryguy
RUN adduser celeryguy sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER celeryguy

# Expose Ports
EXPOSE 8000
ENTRYPOINT ["/celery_entrypoint.sh"]
