# Generated by Django 4.0.3 on 2022-05-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortlistedCandidate',
        ),
    ]
