# Generated by Django 4.0.3 on 2022-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='created_on',
            new_name='created_on_timestamp',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='accepted_at_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
