# Generated by Django 4.0.3 on 2022-03-15 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('u_type', models.CharField(choices=[('Jobseeker', 'Jobseeker'), ('Employer', 'Employer'), ('Super Admin', 'Super Admin')], max_length=15, verbose_name='User Type')),
                ('profile_is_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobseekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='users/photos/%Y/%m/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('masked_contact', models.CharField(default='***********', max_length=15)),
                ('contact_is_verified', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_raters', models.IntegerField(default=0)),
                ('residence', models.CharField(blank=True, max_length=48, null=True)),
                ('zone_1', models.CharField(max_length=128, verbose_name='H3 Zone One')),
                ('zone_2', models.CharField(max_length=128, verbose_name='H3 Zone Two')),
                ('zone_3', models.CharField(max_length=128, verbose_name='H3 Zone Three')),
                ('birth_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'Jobseeker'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=15, null=True, verbose_name='Birth Month')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Birth Year')),
                ('birth_day', models.IntegerField(blank=True, null=True, verbose_name='Birth Day')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=16, null=True, verbose_name='Gender')),
                ('profession', models.CharField(blank=True, max_length=128, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Undergradute Degree', 'Undergradute Degree'), ('Masters Degree', 'Masters Degree')], max_length=48, null=True)),
                ('hourly_rate', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='js_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jobseeker Profile',
                'verbose_name_plural': 'Jobseeker Profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('start_year', models.CharField(blank=True, max_length=4, null=True)),
                ('start_month', models.CharField(blank=True, max_length=16, null=True)),
                ('end_year', models.CharField(blank=True, max_length=4, null=True)),
                ('end_month', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('proficiency_level', models.CharField(choices=[('No Proficiency', 'No Proficiency'), ('Elementary Proficiency', 'Elementary Proficiency'), ('Limited Working Proficiency', 'Limited Working Proficiency'), ('Professional Working Proficiency', 'Professional Working Proficiency'), ('Full Professional Proficiency', 'Full Professional Proficiency'), ('Native or Bilingual Fluency', 'Native or Bilingual Fluency')], max_length=48, verbose_name='Proficiency Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobseekerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=128, null=True)),
                ('file', models.FileField(upload_to='media/documents/%Y/%m/%d/', verbose_name='Document')),
                ('file_status', models.CharField(blank=True, choices=[('Pending State', 'Pending State'), ('Uploading', 'Uploading'), ('Healthy State', 'Healthy State')], default='Pending State', max_length=32, null=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('contact_is_verified', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=96, null=True)),
                ('company_role', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('certification_year', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
