# Generated by Django 4.0.3 on 2022-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='zone_1',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='zone_2',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='zone_3',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
