# Generated by Django 4.0.3 on 2022-03-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_jobseekerprofile_residence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='birth_year',
        ),
    ]
