# Generated by Django 4.0.3 on 2022-03-24 05:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contact_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='contact_is_verified',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='country_code',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='jobseekercontact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='users.jobseekerprofile', verbose_name='Jobseeker contact'),
        ),
    ]
