# Generated by Django 4.0.3 on 2022-03-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_jobseekercontact_remove_jobseekerprofile_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekercontact',
            old_name='user',
            new_name='profile',
        ),
    ]
