# Generated by Django 4.0.3 on 2022-03-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_employerprofile_country_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='total_raters',
            new_name='total_ratings',
        ),
    ]
