# Generated by Django 4.0.3 on 2022-03-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_language_jobseekerlanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerlanguage',
            old_name='user',
            new_name='jobseeker',
        ),
    ]
