# Generated by Django 4.0.3 on 2022-03-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_user_jobseekerlanguage_jobseeker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification',
            new_name='JobseekerCertification',
        ),
    ]
