# Generated by Django 4.0.3 on 2022-03-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_certification_jobseekercertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerlanguage',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
