# Generated by Django 4.0.3 on 2022-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_jobseekerlanguage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerlanguage',
            name='jobseeker',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='languages',
            field=models.ManyToManyField(to='users.jobseekerlanguage'),
        ),
    ]
