# Generated by Django 4.0.3 on 2022-03-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_jobseekerlanguage_jobseeker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobseekerlanguage',
            name='name',
        ),
        migrations.AddField(
            model_name='jobseekerlanguage',
            name='jobseeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseekerlanguage',
            name='proficiency_level',
            field=models.CharField(choices=[('Elementary Proficiency', 'Elementary Proficiency'), ('Limited Working Proficiency', 'Limited Working Proficiency'), ('Professional Working Proficiency', 'Professional Working Proficiency'), ('Full Professional Proficiency', 'Full Professional Proficiency'), ('Native or Bilingual Fluency', 'Native or Bilingual Fluency')], max_length=48, verbose_name='Proficiency Level'),
        ),
        migrations.AddField(
            model_name='jobseekerlanguage',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.language'),
            preserve_default=False,
        ),
    ]
