# Generated by Django 4.0.3 on 2022-03-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_jobseekerlanguage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerlanguage',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.language', verbose_name='Language'),
        ),
    ]
