# Generated by Django 4.0.3 on 2022-03-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_jobseekerlanguage_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='languages',
        ),
    ]
