# Generated by Django 4.0.3 on 2022-03-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_jobseekerprofile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerlanguage',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_spoken_languages', to='users.language', verbose_name='Language'),
        ),
    ]
