# Generated by Django 4.0.3 on 2022-03-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_jobseekerlanguage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerlanguage',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_spoken_languages', to='users.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='jobseekerlanguage',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.language', verbose_name='Language'),
        ),
    ]
