# Generated by Django 4.0.3 on 2022-03-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_jobseekerlanguage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'Jobseeker'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=16, null=True, verbose_name='End month'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.IntegerField(null=True, verbose_name='End year'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'Jobseeker'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=16, null=True, verbose_name='Start month'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.IntegerField(null=True, verbose_name='Start year'),
        ),
    ]
