# Generated by Django 4.0.3 on 2022-03-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_workexperience_end_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='hourly_rate',
        ),
    ]
