# Generated by Django 4.0.3 on 2022-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_jobseekerprofile_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='role',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'Jobseeker'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=1, max_length=16, verbose_name='End month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.IntegerField(default=1, verbose_name='End year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'Jobseeker'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=1, max_length=16, verbose_name='Start month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.IntegerField(default=1, verbose_name='Start year'),
            preserve_default=False,
        ),
    ]
