# Generated by Django 4.0.3 on 2022-03-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_workexperience_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekercertification',
            name='certification_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercertification',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
