# Generated by Django 4.0.3 on 2022-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_jobseekercertification_certification_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekercertification',
            name='certification_year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseekercertification',
            name='title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
