# Generated by Django 4.0.3 on 2022-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_jobseekercertification_certification_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='education_level',
            field=models.CharField(choices=[('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Undergradute Degree', 'Undergradute Degree'), ('Masters Degree', 'Masters Degree')], max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profession',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
