# Generated by Django 4.0.3 on 2022-03-27 09:53

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_jobseekerprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_role',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='masked_contact',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='users/photos/%Y/%m/'),
        ),
    ]
