# Generated by Django 4.0.3 on 2022-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_jobseekerdocument_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='identification_card',
            field=models.FileField(default=11, upload_to='media/documents/%Y/%m/%d/', verbose_name='Identification Card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='w2_document',
            field=models.FileField(default=1, upload_to='media/documents/%Y/%m/%d/', verbose_name='W2 Document'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobseekerDocument',
        ),
    ]
