# Generated by Django 4.0.3 on 2022-03-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_jobseekerprofile_identification_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerprofile',
            options={'ordering': ['-avg_rating'], 'verbose_name': 'Jobseeker Profile', 'verbose_name_plural': 'Jobseeker Profiles'},
        ),
    ]
