# Generated by Django 4.0.3 on 2022-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_jobseekerprofile_identification_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='hourly_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='JobseekerDocuments',
        ),
    ]
