# Generated by Django 4.0.3 on 2022-04-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_workexperience_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='jobseeker',
            new_name='profile',
        ),
    ]
