# Generated by Django 4.0.3 on 2022-04-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_remove_jobseekerlanguage_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerlanguage',
            old_name='jobseeker',
            new_name='profile',
        ),
    ]
