# Generated by Django 4.0.3 on 2022-04-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_rename_jobseeker_jobseekercertification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekercertification',
            name='certification_year',
            field=models.PositiveIntegerField(),
        ),
    ]
