# Generated by Django 4.0.3 on 2022-04-05 09:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_jobseekercertification_certification_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='media/users/photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='media/users/photos/%Y/%m/'),
        ),
    ]
