# Generated by Django 4.0.3 on 2022-04-06 17:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_employerprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='users/photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='users/photos/%Y/%m/'),
        ),
    ]
