# Generated by Django 4.0.3 on 2022-04-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_employerprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='education_level',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Undergradute Degree', 'Undergradute Degree'), ('Masters Degree', 'Masters Degree')], max_length=48, null=True),
        ),
    ]
