# Generated by Django 4.0.3 on 2022-04-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_jobseekerprofile_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='education_level',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Undergraduate Degree', 'Undergraduate Degree'), ('Masters Degree', 'Masters Degree')], max_length=48, null=True),
        ),
    ]
