# Generated by Django 4.0.3 on 2022-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_jobseekerprofile_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
