# Generated by Django 4.0.3 on 2022-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_employerprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='subscription_status',
            field=models.CharField(default='inactive', max_length=32),
        ),
    ]
