# Generated by Django 4.0.3 on 2022-04-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_employerprofile_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='sub_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='sub_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
