# Generated by Django 4.0.3 on 2022-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_alter_employerprofile_current_sub_period_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='verified',
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='subscription_status',
            field=models.CharField(default='no_subscription', max_length=32),
        ),
    ]
