# Generated by Django 4.0.3 on 2022-04-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_userdocument_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterModelOptions(
            name='userdocument',
            options={'ordering': ['-id'], 'verbose_name': 'User Document', 'verbose_name_plural': 'User Documents'},
        ),
    ]
