# Generated by Django 4.0.3 on 2022-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_remove_employerprofile_current_sub_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=16, null=True, verbose_name='Gender'),
        ),
    ]
