# Generated by Django 4.0.3 on 2022-05-04 18:56

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_employerprofile_birthday_employerprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='media/users/photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='media/users/photos/%Y/%m/'),
        ),
    ]
