# Generated by Django 4.0.3 on 2022-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_employerprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='latitude',
            field=models.CharField(default=213, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='longitude',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
