# Generated by Django 4.0.3 on 2022-05-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_jobseekerprofile_latitude_jobseekerprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='longitude',
        ),
    ]
