# Generated by Django 4.0.3 on 2022-05-16 11:49

from django.db import migrations, models
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_delete_userdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='contact_is_verified',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_is_complete',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='media/users/photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non Binary', 'Non Binary'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=16, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non Binary', 'Non Binary'), ('Unspecified', 'Unspecified')], max_length=16, null=True, verbose_name='Gender'),
        ),
    ]
