# Generated by Django 4.0.3 on 2022-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_jobseekerprofile_profile_completeness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_type',
        ),
        migrations.AddField(
            model_name='user',
            name='logged_in_as',
            field=models.CharField(choices=[('Jobseeker', 'Jobseeker'), ('Employer', 'Employer'), ('Veeta Staff', 'Veeta Staff')], default='Jobseeker', max_length=15, verbose_name='User Type'),
        ),
    ]
