# Generated by Django 4.0.3 on 2022-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_remove_employerprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logged_in_as',
            field=models.CharField(choices=[('Jobseeker', 'Jobseeker'), ('Employer', 'Employer'), ('Veeta Staff', 'Veeta Staff'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=15, verbose_name='Logged in as'),
        ),
    ]
