# Generated by Django 4.0.3 on 2022-05-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_alter_user_logged_in_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_type',
            field=models.CharField(choices=[('General', 'General'), ('Veeta Staff', 'Veeta Staff'), ('Veeta Superuser', 'Veeta Super User')], default='General', max_length=15, verbose_name='u_type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logged_in_as',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Jobseeker', 'Jobseeker'), ('Veeta Staff', 'Veeta Staff'), ('Veeta Superuser', 'Veeta Super User')], default='Employer', max_length=15, verbose_name='Logged in as'),
        ),
    ]
