# Generated by Django 4.0.3 on 2022-05-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_user_u_type_alter_user_logged_in_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='u_type',
            field=models.CharField(choices=[('General', 'General'), ('Veeta Staff', 'Veeta Staff'), ('Veeta Superuser', 'Veeta Super User')], default='General', max_length=15, verbose_name='User type'),
        ),
    ]
