# Generated by Django 4.0.3 on 2022-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_employerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
