# Generated by Django 4.0.3 on 2022-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_jobseekerprofile_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='is_published',
        ),
        migrations.AddField(
            model_name='user',
            name='publish_jobseeker_profile',
            field=models.BooleanField(default=True),
        ),
    ]
