# Generated by Django 4.0.3 on 2022-05-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_remove_jobseekerlanguage_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_completeness',
            field=models.IntegerField(default=0),
        ),
    ]
