# Generated by Django 4.0.3 on 2022-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_alter_jobseekerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_notifications',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
