# Generated by Django 4.0.3 on 2022-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_user_unread_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email_notification',
            field=models.DateTimeField(null=True),
        ),
    ]
