# Generated by Django 4.0.3 on 2022-10-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_jobseekerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='courses',
        ),
    ]
