# Generated by Django 4.0.3 on 2022-05-11 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0021_remove_jobcard_latitude_remove_jobcard_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.jobcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Bookmark',
                'verbose_name_plural': 'Job Bookmarks',
                'ordering': ['-id'],
            },
        ),
    ]
