version: "3.3"
services:
  # Nginx
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.dev
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

  # Redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always

  # Celery Worker for the Backend
  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile.dev
    container_name: celery
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - backend
      - redis
    # command: celery -A core.settings worker -l INFO
    volumes:
      - .:/django

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: django_backend
    restart: unless-stopped
    volumes:
      - .:/django
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres

  # Stripe Webhook
  stripe:
    image: stripe/stripe-cli:latest
    container_name: stripe_wh_listener
    restart: unless-stopped
    command: listen --api-key ${VEETA_STRIPE_SECRET_KEY} --forward-to backend:8000/payments/webhook/

  # PostgresDB for the Backend
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ./postgres_dev/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
