version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: veeta:v1.0.8
    env_file:
      - ./env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh"
