# Generated by Django 4.0.3 on 2022-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobseekers', models.IntegerField(default=0)),
                ('total_employers', models.IntegerField(default=0)),
            ],
        ),
    ]
