# Generated by Django 4.0.3 on 2022-05-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobBookmark',
        ),
    ]
