# Generated by Django 4.0.3 on 2022-05-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0078_remove_jobseekerlanguage_profile_and_more'),
        ('jobseekers', '0002_delete_jobbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('start_year', models.PositiveIntegerField(verbose_name='Start year')),
                ('end_year', models.PositiveIntegerField(verbose_name='End year')),
                ('start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'Jobseeker'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=16, verbose_name='Start month')),
                ('end_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'Jobseeker'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=16, null=True, verbose_name='End month')),
                ('currently_working_here', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_experience', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobseekerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Language')),
                ('proficiency_level', models.CharField(choices=[('Elementary Proficiency', 'Elementary Proficiency'), ('Limited Working Proficiency', 'Limited Working Proficiency'), ('Professional Working Proficiency', 'Professional Working Proficiency'), ('Full Professional Proficiency', 'Full Professional Proficiency'), ('Native or Bilingual Fluency', 'Native or Bilingual Fluency')], max_length=48, verbose_name='Proficiency Level')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_spoken_languages', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobseekerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('certification_year', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_certifications', to='users.jobseekerprofile')),
            ],
        ),
    ]
