# Generated by Django 4.0.3 on 2022-05-19 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseekers', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobseekerLanguage',
            new_name='UserLanguage',
        ),
        migrations.RemoveField(
            model_name='userlanguage',
            name='profile',
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_spoken_languages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
