# Generated by Django 4.0.3 on 2022-05-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_remove_jobseekerlanguage_profile_and_more'),
        ('jobseekers', '0004_rename_jobseekerlanguage_userlanguage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Language')),
                ('proficiency_level', models.CharField(choices=[('Elementary Proficiency', 'Elementary Proficiency'), ('Limited Working Proficiency', 'Limited Working Proficiency'), ('Professional Working Proficiency', 'Professional Working Proficiency'), ('Full Professional Proficiency', 'Full Professional Proficiency'), ('Native or Bilingual Fluency', 'Native or Bilingual Fluency')], max_length=48, verbose_name='Proficiency Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='users.jobseekerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserLanguage',
        ),
    ]
