# Generated by Django 4.0.3 on 2022-05-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0005_jobseekerlanguage_delete_userlanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerlanguage',
            old_name='user',
            new_name='profile',
        ),
    ]
