# Generated by Django 4.0.3 on 2022-03-15 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerrating',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerrating',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.company'),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
