# Generated by Django 4.0.3 on 2022-04-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_jobseekerrating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyrating',
            options={'ordering': ['-id'], 'verbose_name': 'Company Rating', 'verbose_name_plural': 'Company Ratings'},
        ),
        migrations.AlterModelOptions(
            name='jobseekerrating',
            options={'ordering': ['-id'], 'verbose_name': 'Jobseeker Rating', 'verbose_name_plural': 'Jobseeker Ratings'},
        ),
    ]
