# Generated by Django 4.0.3 on 2022-03-15 10:28

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('tag', models.CharField(choices=[('Main Branch', 'Main Branch'), ('Sub Branch', 'Sub Branch')], max_length=64, verbose_name='Tag')),
                ('longitude', models.CharField(max_length=64, verbose_name='Longitude')),
                ('latitude', models.CharField(max_length=64, verbose_name='Latitude')),
                ('zone_1', models.CharField(blank=True, max_length=64, null=True, verbose_name='H3 Zone One')),
                ('zone_2', models.CharField(blank=True, max_length=64, null=True, verbose_name='H3 Zone Two')),
                ('zone_3', models.CharField(blank=True, max_length=64, null=True, verbose_name='H3 Zone Three')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('logo', imagekit.models.fields.ProcessedImageField(default='default_logo.jpg', upload_to='media/establishments/companies/logo/%Y/%m/')),
                ('website_url', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('contract_type', models.CharField(choices=[('Hourly Pay', 'Hourly Pay'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Hourly Pay', max_length=32, verbose_name='Contract Type')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('taken', models.BooleanField(default=False)),
                ('branches_available', models.ManyToManyField(to='establishments.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.company')),
            ],
            options={
                'verbose_name': 'Job Vacancy',
                'verbose_name_plural': 'Job Vacancies',
            },
        ),
    ]
