# Generated by Django 4.0.3 on 2022-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='jobvacancy',
            options={'ordering': ['-id'], 'verbose_name': 'Job Vacancy', 'verbose_name_plural': 'Job Vacancies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(),
        ),
    ]
