# Generated by Django 4.0.3 on 2022-03-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0003_alter_company_options_alter_jobvacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-id'], 'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
    ]
