# Generated by Django 4.0.3 on 2022-03-29 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_alter_jobapplication_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('contract_type', models.CharField(choices=[('Hourly Gig', 'Hourly Gig'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Hourly Gig', max_length=32, verbose_name='Contract Type')),
                ('location', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('taken', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.company')),
            ],
            options={
                'verbose_name': 'Job Vacancy',
                'verbose_name_plural': 'Job Vacancies',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.jobdescription')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='branches_available',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='company',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='establishments.jobdescription', verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacancy_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='establishments.jobcard'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.jobcard'),
        ),
        migrations.DeleteModel(
            name='JobVacancy',
        ),
    ]
