# Generated by Django 4.0.3 on 2022-03-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_jobcard_jobdescription_jobresponsibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-id'], 'verbose_name': 'Job Card', 'verbose_name_plural': 'Job Cards'},
        ),
        migrations.AddField(
            model_name='jobcard',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='application_deadline',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='establishments.jobcategory'),
            preserve_default=False,
        ),
    ]
