# Generated by Django 4.0.3 on 2022-03-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0006_jobcategory_alter_jobcard_options_jobcard_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobresponsibility',
            name='description',
        ),
        migrations.AddField(
            model_name='jobresponsibility',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='establishments.jobcard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
