# Generated by Django 4.0.3 on 2022-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0007_remove_jobresponsibility_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='contract_type',
            field=models.CharField(choices=[('Hourly Gig', 'Hourly Gig'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=32, verbose_name='Contract Type'),
        ),
    ]
