# Generated by Django 4.0.3 on 2022-04-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0008_alter_jobcard_contract_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='vacancy_applied',
        ),
    ]
