# Generated by Django 4.0.3 on 2022-04-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0010_rename_created_on_employee_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
