# Generated by Django 4.0.3 on 2022-04-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0011_alter_jobcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='vacancy',
            new_name='card',
        ),
    ]
