# Generated by Django 4.0.3 on 2022-04-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0014_delete_jobcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='pay',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
