# Generated by Django 4.0.3 on 2022-04-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0015_jobcard_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
