# Generated by Django 4.0.3 on 2022-04-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0018_alter_company_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='location',
        ),
    ]
