# Generated by Django 4.0.3 on 2022-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0019_rename_city_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='latitude',
            field=models.CharField(default=1213, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='longitude',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
