# Generated by Django 4.0.3 on 2022-05-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0020_jobcard_latitude_jobcard_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='longitude',
        ),
    ]
