# Generated by Django 4.0.3 on 2022-05-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0021_remove_jobcard_latitude_remove_jobcard_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='establishments.jobcard'),
        ),
    ]
