# Generated by Django 4.0.3 on 2022-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0022_alter_jobapplication_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='positions_available',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
