# Generated by Django 4.0.3 on 2022-05-17 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0023_jobcard_positions_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hiring_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
