# Generated by Django 4.0.3 on 2022-05-21 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0024_alter_company_hiring_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='establishments.company'),
        ),
    ]
