# Generated by Django 4.0.3 on 2022-05-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0025_alter_jobcard_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='establishments.company'),
        ),
    ]
