# Generated by Django 4.0.3 on 2022-05-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0028_alter_jobcard_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='desc',
        ),
    ]
