# Generated by Django 4.0.3 on 2022-05-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0029_remove_jobcard_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
