# Generated by Django 4.0.3 on 2022-06-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0030_alter_jobcard_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='approved',
            new_name='make_offer',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='accept_offer',
            field=models.BooleanField(default=False),
        ),
    ]
