# Generated by Django 4.0.3 on 2022-06-10 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0031_rename_approved_jobapplication_make_offer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='card',
            new_name='job_card',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='accept_offer',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='make_offer',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
