# Generated by Django 4.0.3 on 2022-10-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_jobseekerprofile_user'),
        ('establishments', '0033_coursecard_lessonsmodule_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='completed',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.lessonsmodule'),
        ),
    ]
