# Generated by Django 4.0.3 on 2022-10-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_jobseekerprofile_user'),
        ('establishments', '0034_alter_completed_by_alter_completed_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed',
            name='by',
        ),
        migrations.CreateModel(
            name='Enrolments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile')),
                ('course', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='establishments.coursecard')),
            ],
        ),
        migrations.AddField(
            model_name='completed',
            name='enrolment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establishments.enrolments'),
        ),
    ]
