# Generated by Django 4.0.3 on 2022-05-29 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0079_alter_jobseekerprofile_profile_completeness'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('unlock_code', models.CharField(max_length=32, null=True)),
                ('total_unlocks', models.PositiveIntegerField(default=0)),
                ('job_cards', models.PositiveIntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Access Credit',
                'verbose_name_plural': 'User Access Credits',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnlockedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('access_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_unlock.useraccesscredit')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Unlocked Profile',
                'verbose_name_plural': 'Unlocked Profiles',
                'ordering': ['-id'],
            },
        ),
    ]
