# Generated by Django 4.0.3 on 2022-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_unlock', '0003_alter_useraccesscredit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccesscredit',
            name='tag',
            field=models.CharField(default='sign_up_trial_credits', max_length=32),
            preserve_default=False,
        ),
    ]
