# Generated by Django 4.0.3 on 2022-05-04 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0019_rename_city_company_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserZoneMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_one', models.CharField(max_length=256)),
                ('zone_two', models.CharField(max_length=256)),
                ('zone_three', models.CharField(max_length=256)),
                ('zone_four', models.CharField(max_length=256)),
                ('zone_five', models.CharField(max_length=256)),
                ('zone_six', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobCardZoneMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_one', models.CharField(max_length=256)),
                ('zone_two', models.CharField(max_length=256)),
                ('zone_three', models.CharField(max_length=256)),
                ('zone_four', models.CharField(max_length=256)),
                ('zone_five', models.CharField(max_length=256)),
                ('zone_six', models.CharField(max_length=256)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.jobcard')),
            ],
        ),
    ]
