# Generated by Django 4.0.3 on 2022-05-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardzonemetadata',
            name='zone_six',
        ),
        migrations.RemoveField(
            model_name='userzonemetadata',
            name='zone_six',
        ),
    ]
