# Generated by Django 4.0.3 on 2022-05-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0019_rename_city_company_location'),
        ('utils', '0002_remove_jobcardzonemetadata_zone_six_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardzonemetadata',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_metadata', to='establishments.jobcard'),
        ),
    ]
