# Generated by Django 4.0.3 on 2022-05-05 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0020_jobcard_latitude_jobcard_longitude'),
        ('utils', '0003_alter_jobcardzonemetadata_job_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardzonemetadata',
            name='zone_eight',
            field=models.CharField(default=2123, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcardzonemetadata',
            name='zone_seven',
            field=models.CharField(default=21, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcardzonemetadata',
            name='zone_six',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcardzonemetadata',
            name='job_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_metadata', to='establishments.jobcard'),
        ),
        migrations.AlterField(
            model_name='userzonemetadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_metadata', to=settings.AUTH_USER_MODEL),
        ),
    ]
