# Generated by Django 4.0.3 on 2022-05-05 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0005_remove_jobcardzonemetadata_zone_eight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userzonemetadata',
            name='zone_seven',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userzonemetadata',
            name='zone_six',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userzonemetadata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_metadata', to=settings.AUTH_USER_MODEL),
        ),
    ]
