# Generated by Django 4.0.3 on 2022-04-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicationnotification',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='jobapplicationnotification',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
