# Generated by Django 4.0.3 on 2022-04-29 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_remove_jobapplicationnotification_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplicationnotification',
            options={'ordering': ['-id'], 'verbose_name': 'Job Application Notification', 'verbose_name_plural': 'Job Application Notifications'},
        ),
        migrations.AddField(
            model_name='jobapplicationnotification',
            name='user',
            field=models.ForeignKey(default=326, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
