# Generated by Django 4.0.3 on 2022-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_jobapplicationnotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationnotification',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
