# Generated by Django 4.0.3 on 2022-04-30 07:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_jobapplicationnotification_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplicationNotification',
            new_name='UserNotification',
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-id'], 'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notifications'},
        ),
    ]
