# Generated by Django 4.0.3 on 2022-05-31 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_rename_jobapplicationnotification_usernotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='sent',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='mark_as_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
