# Generated by Django 4.0.3 on 2022-06-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_emailnotificationlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotificationlog',
            old_name='last_sent_on',
            new_name='sent_on',
        ),
    ]
