# Generated by Django 4.0.3 on 2022-06-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_emailnotificationlog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotificationLog',
        ),
    ]
