# Generated by Django 4.0.3 on 2022-06-05 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0030_alter_jobcard_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0013_delete_emailnotificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationNotificationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.jobcard')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='job_application_metadata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.jobapplicationnotificationmetadata'),
        ),
    ]
