# Generated by Django 4.0.3 on 2022-06-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationnotificationmetadata',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_metadata', to='notifications.notification'),
        ),
    ]
