# Generated by Django 4.0.3 on 2022-06-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_alter_jobapplicationnotificationmetadata_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicationnotificationmetadata',
            old_name='jobseeker',
            new_name='user',
        ),
    ]
