# Generated by Django 4.0.3 on 2022-10-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_notification_job_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tag',
            field=models.CharField(choices=[('new_chat_message', 'new_chat_message'), ('new_job_application', 'new_job_application'), ('new_job_offer', 'new_job_offer')], max_length=64),
        ),
    ]
